default: &default
  adapter: postgresql
  encoding: utf8
  #host: database
  #username: postgres
  #password: postgres
  #database: docker_rails_dev
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: docker_rails_dev

production:
  <<: *default
